# Generated by Django 6.0.3 on 2026-04-07 19:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="accounts.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceiptLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("product_description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name="ProcessedReceipt",
            fields=[
                (
                    "receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="processed",
                        serialize=False,
                        to="scanning.receipt",
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "total_discounts",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("processed_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="ReceiptError",
            fields=[
                (
                    "receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="error",
                        serialize=False,
                        to="scanning.receipt",
                    ),
                ),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ReceiptResult",
            fields=[
                (
                    "receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="result",
                        serialize=False,
                        to="scanning.receipt",
                    ),
                ),
                ("raw_json", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="ReceiptImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(upload_to="receipts/%Y/%m/%d/")),
                ("sequence", models.PositiveSmallIntegerField(default=0)),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="scanning.receipt",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="LineItemDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.CharField(default="Discount", max_length=255)),
                (
                    "line_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="scanning.receiptlineitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sellers",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "organization")},
            },
        ),
        migrations.CreateModel(
            name="PointOfSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("address", models.TextField()),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_of_sale",
                        to="scanning.seller",
                    ),
                ),
            ],
            options={
                "unique_together": {("seller", "address")},
            },
        ),
        migrations.CreateModel(
            name="SellerOrderId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("identifier", models.CharField(max_length=255)),
                (
                    "processed_receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_order_info",
                        to="scanning.processedreceipt",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="receiptlineitem",
            name="processed_receipt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="scanning.processedreceipt",
            ),
        ),
        migrations.AddField(
            model_name="processedreceipt",
            name="point_of_sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipts",
                to="scanning.pointofsale",
            ),
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("method", models.CharField(max_length=100)),
                (
                    "processed_receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_info",
                        to="scanning.processedreceipt",
                    ),
                ),
            ],
        ),
    ]
