# Generated by Django 6.0.3 on 2026-03-31 23:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PointOfSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProcessedReceipt",
            fields=[
                (
                    "receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="processed",
                        serialize=False,
                        to="scanning.receipt",
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "total_discounts",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("processed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "point_of_sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="scanning.pointofsale",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(max_length=100)),
                (
                    "processed_receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_info",
                        to="scanning.processedreceipt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceiptLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "processed_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="scanning.processedreceipt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LineItemDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "description",
                    models.CharField(default="Discount", max_length=255),
                ),
                (
                    "line_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="scanning.receiptlineitem",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pointofsale",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="points_of_sale",
                to="scanning.seller",
            ),
        ),
        migrations.CreateModel(
            name="SellerOrderId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=255)),
                (
                    "processed_receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_order_info",
                        to="scanning.processedreceipt",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="pointofsale",
            unique_together={("seller", "address")},
        ),
    ]
