# Generated by Django 6.0.3 on 2026-04-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanning", "0002_rls"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipterror",
            name="code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("E001", "Budget Exceeded"),
                    ("E101", "Response Truncated"),
                    ("E102", "Invalid JSON Format"),
                    ("E103", "Provider API Error"),
                ],
                max_length=4,
                null=True,
            ),
        ),
    ]
