services:
  db:
    image: postgres:18-trixie
    restart: always
    environment:
      POSTGRES_DB: finis
      POSTGRES_USER: finis
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql:rw

volumes:
  postgres_data:
